#!/usr/bin/env bash
# Install nginx and configure a redirection

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'NGINX HTTP'
sudo chmod -R 755 /var/www
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i 'listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites_available/default
sudo service nginx start
