#!/usr/bin/env bash
# Add custom header to nginx config

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'NGINX HTTP'
sudo sed -i 's/server_name _\;/server_name _\;\n\tadd_header X-Served-By $hostname always;/g'  /etc/nginx/sites-enabled/default
sudo service nginx restart
