#!/usr/bin/env bash
# Does the following:
#  Creates a file /var/run/myscript.pid containing the script pid
#  Display "To infinity and beyond" indefinitely
#  Displays "I hate the kill command" upon recieving a SIGTERM
#  Displays "Y U no love me?!" upon receiving a SIGINT
#  Deletes the file "/var/run/myscript.pid" upon receiving
#+ a SIGTERM or SIGQUIT

terminator() {
	rm /var/run/myscript.pid
	exit
}

echo "$$" > /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command" && terminator' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'terminator' SIGQUIT
done
