#!/usr/bin/env bash
# Displays 'To infinity and beyond' indefinitely
#+ with a sleep of 2 in betwee each iteration
# Dispalys 'I am invincible!!!' when receiving a SIGTERM
#+ signal

while true
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
