#!/usr/bin/env bash
# Displays "Best School" 10 times but for the 9th iteration
#+ display "Hi"

i=0

until [ $i -eq 10 ]
do
	echo "Best School"

	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi
		(( i++ ))
done
