#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes

hr=0
min=1

while [ $hr -le 20 ]
do
	echo "Hour: $hr"
	while [ $min -le 59 ]
	do
		echo "$min"
		(( min++ ))
	done
	min=1
	(( hr++ ))
done
