#!/usr/bin/env bash
# Configures an Ubuntu server
#  localhost resolves to 127.0.0.2
#  facebook.com resolves to 8.8.8.8

sudo cp /etc/hosts my_host
sed -i s/127\.0\.0\.1.*/"127.0.0.2	localhost"/ my_host
echo "8.8.8.8	facebook.com" >> my_host
sudo cp my_host /etc/hosts
